version: '3.1'

volumes:
  dbdata-vol:
  dbdata-replica-vol:
  redisdata-vol:

services:
  pg-master:
    build: '.'
    image: 'danieldent/postgres-replication'
    privileged: true
    restart: unless-stopped
    environment:
      POSTGRES_USER: dockerizame
      POSTGRES_PASSWORD: dockerizame
      POSTGRES_DB: dockerizame
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
     - dbdata-vol:/var/lib/postgresql/data
    ports:
    - "25432:5432"
    expose:
     - "5432"

  pg-slave:
    build: '.'
    image: 'danieldent/postgres-replication'
    privileged: true
    restart: unless-stopped
    environment:
      POSTGRES_USER: dockerizame
      POSTGRES_PASSWORD: dockerizame
      POSTGRES_DB: dockerizame
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: pg-master
    volumes:
     - dbdata-replica-vol:/var/lib/postgresql/data
    depends_on:
      - pg-master
    expose:
     - "5432"

  redis:
    image: redis
    ports:
    - "26379:6379"
    volumes:
      - redisdata-vol:/data
    depends_on:
      - pg-master
